[allowlist]
description = "Merged allowlist"
rules = [
  "generic-api-key"
]
paths = [
  "Zeus.Form/app.config",
  "Zeus.Form/formWizard.resx",
  "MapeadorDeEntidades.Form/formPrincipal.resx",
  "MapeadorDeEntidades.Form/app.config",
  "MapeadorDeEntidades.Form/Core/NewProgressBar.resx"
]
